#!/usr/bin/env bash
set -e  # Exit on any error
# deploy - Provision VPS
# Usage:  deploy <remote> [=]
#   <remote>:  Host from ~/.ssh/config
#   If '=' is given, setting up the authorized key is skipped
# Actions:
# * Set up authorized_keys [optional]
# * Copy this script to remote
# * Execute it with .<myid>
#   - Update repo
#   - Install basic software
#   - Configure TZ
#   - Uninstall snap (Ubuntu)
#   - Get github.com/pepa65/misc
#   - Install nano (from source) and tmux

prov=$0 remote=$1 myid=$(</etc/machine-id)

Inf(){	# 1:msg
	echo "-- $1"
}
Err(){ # 1:msg 2:ret
	echo "## $1"
	exit $2
}

# Priming remote
if [[ $remote && ! ${remote:0:1} = . ]]
then # Host specified and not an ID
	[[ $2 != = ]] &&
		Inf "Setting up authorized_keys on $remote" &&
		ssh-copy-id -i ~/.ssh/id_ed25519.pub "$remote"
	Inf "Copying '$prov' from $myid to $remote..."
	scp -q "$prov" "$1":
	prov=${prov##*/}
	Inf "Executing '$prov' on $remote..."
	ssh "$1" "bash $prov" ".$myid"
	exit
fi

# On the remote already?
[[ -z $1 ]] &&
	Err "Need HOST (from ~/.ssh/config)" 1

# On the remote already??
me=$(whoami) id=$(</etc/machine-id) fromid=${1:1}
[[ $fromid = $id ]] &&
	Err "Same machine, exiting" 2

Inf "User $me on $id (from $fromid): $(hostname -A)"

# On the remote!
set -xv
sudo -S apt update
sudo -S dpkg-reconfigure tzdata
sudo -S apt-get install -y ne dfc iftop iotop colordiff dwdiff caca-utils git tmux aptitude rsync csvtool jq psmisc lsof telnet
sudo -S apt purge snapd
[[ -d git ]] || mkdir git
cd git
[[ ! -d misc ]] && git clone https://gitlab.com/pepa65/misc && misc/buildnano && sudo -S ln -sf ~/.nanorc /root/
if [[ ! -f ~/.tmux.conf ]]
then
	cp misc/.tmux.conf ~/
	echo -e "\n#PP\nsource ~/git/misc/pp\n" >>~/.bashrc
	echo -e "\n#PP\nsource $HOME/git/misc/pp\n" |sudo -S tee -a /root/.bashrc
fi

# Install c & l
wget 4e4.in/c
wget 4e4.in/l
chmod +x c l
sudo mv c l /usr/local/bin/
sudo chown root:root /usr/local/bin/*
