#!/bin/bash
set +vx
# difth - show the difference between 2 Thai language files in html or terminal
## Required: swath dwdiff sed coreutils(cat type mktemp rm)

## Color scheme
font="black" paper="white" back="#bbb" header="#888" hfont="black"
oldf="black" oldp="#fcc" oldb=$oldp newf="black" newp="#cfc" newb=$newp
#oldf="red" oldp=$paper oldb="pink" newf="darkgreen" newp=$paper newb="lightgreen"

Help(){
	cat <<-EOF
		 $(basename $0) - Show the differences between 2 Thai language input files
		  and either produce a html file, or output result to the terminal
		 USAGE:  $0 <file1> <file2> [<html-out>]
		   file1 and file2 are mandatory, html-out is optional (otherwise to stdout)
		   While viewing the html: click to cycle through the display modes.
	EOF
}

! type -p swath &>/dev/null && echo "ABORT: package swath not installed" && exit 1
! type -p dwdiff &>/dev/null && echo "ABORT: package dwdiff not installed" && exit 2
[[ -z $2 ]] && Help && echo "ABORT: At least 2 filenames necessary" && exit 3
[[ $4 ]] && Help && echo "ABORT: More than 3 arguments" && exit 4
[[ ! -f $1 ]] && Help && echo "ABORT: First argument no file: $1" && exit 
[[ ! -f $2 ]] && Help && echo "ABORT: Second argument no file: $2" && exit 6
[[ $1 = $2 ]] && ai=$(readlink -e	"$1") bi=$(readlink -e "$2") || ai=$1 bi=$2
tmp=$(mktemp -d) at="$tmp/at" bt="$tmp/bt" st="$tmp/st"

## unique separators: $d:delimiter $o:old-begin $e:end $n:new-begin
d="{d$RANDOM}" o="{o$RANDOM}" e="{e$RANDOM}" n="{n$RANDOM}"
grep -e $d -e $o -e $e -e $n "$1" || grep -e $d -e $o -e $e -e $n "$2" &&
	echo "ABORT: separator $d, $o, $e or $n present in input files" && exit 7

as=$(swath -b "$d" -u u,u <"$ai")
bs=$(swath -b "$d" -u u,u <"$bi")

if [[ $3 ]]
then  ## html
	sed -e 's@  @\&nbsp; @g' -e 's@\t@<span class="t"></span> @g' <<<"$as" >"$at"
	sed -e 's@  @\&nbsp; @g' -e 's@\t@<span class="t"></span> @g' <<<"$bs" >"$bt"
	ci=$(dwdiff -s -R -A best -d $d -w $o -x $e -y $n -z $e "$at" "$bt" 2>"$st" |\
		sed -e "s@$d@@g" -e 's@^@<br />@g' -e "s@$e@</span>@g"\
				-e "s@$n@<span class=\"n\">@g" -e "s@$o@<span class=\"o\">@g")
	cat <<EOF >"$3"
<html lang="th">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>$1 / $2</title>
<script type="application/javascript">
//<![CDATA[<!--
view=0;
window.onclick = function (){
	view=(++view%3);
	var s, i;
	if(view==0){ // both
		document.body.style.background="$back";
		s=document.getElementsByClassName("o");
		for(i=0; i<s.length; i++) s[i].style.display="inline";} // was hidden
	else if(view==1){ // old
		document.body.style.background="$oldb";
		s=document.getElementsByClassName("n");
		for(i=0; i<s.length; i++) s[i].style.display="none";
		s=document.getElementsByClassName("o");
		for(i=0; i<s.length; i++) s[i].style.background="oldp";}
	else { // new
		document.body.style.background="$newb";
		s=document.getElementsByClassName("o");
		for(i=0; i<s.length; i++) s[i].style.display="none";
		s=document.getElementsByClassName("n");
		for(i=0; i<s.length; i++) s[i].style.display="inline";}}
//-->]]>
</script>
<style type="text/css">
body {background:$back; color:$font; font-size:150%; font-family:Arundina Serif,serif}
h1 {text-align:center; font-size:80%}
span.t {display:inline-block; width:3em}
span.o {color:$oldf; background:$oldp; text-decoration:line-through}
span.n {color:$newf; background:$newp; text-decoration:underline}
h1 span.o {padding:0 0.2em}
h1 span.n {padding:0 0.2em}
div.h {color:$hfont; background:$header; padding:0.2}
pre {margin-left:0.5em}
div {background:$paper; padding:0.5em}
</style>
</head>
<body title="Click to show: comparison / original / corrected&#013;คลิกเพื่อแสดง การเปรียบเทียบ / ต้นฉบับ / ฉบับแก้ไข">
<div class="h">
<h1><span class="o">$ai</span> <span class="n">$bi</span></h1>
<pre>
$(cat "$st" |sed  -e 's@old@เก่า@g'  -e 's@new@ใหม่@g' -e 's@words@คำ@g'\
		-e 's@common@ตรงกัน@g' -e 's@deleted@ลบ   @g' -e 's@inserted@แทรก@g'\
		-e 's@changed@เปลี่ยน@g')
</pre>
</div>
<div>
$ci
</div>
</body>
</html>
EOF

else  ## terminal
	echo "$as" >"$at"
	echo "$bs" >"$bt"
	ci=$(dwdiff -s -R -A best -d $d -w $o -x $e -y $n -z $e "$at" "$bt" 2>"$st" |\
		sed -e "s@$d@@g" -e "s@$n@$(echo $'\o33\[7;4;32m')@g"\
				-e "s@$o@$(echo $'\o33\[7;4;31m')@g" -e "s@$e@$(echo $'\o33\[0m')@g")
	echo -e "$ci"
	echo '--------------------------------------------------------------------------------'
	cat "$st" |sed -e 's@old@เก่า@g'  -e 's@new@ใหม่@g' -e 's@words@คำ@g'\
			-e 's@common@ตรงกัน@g' -e 's@deleted@ลบ  @g' -e 's@inserted@แทรก@g'\
			-e 's@changed@เปลี่ยน@g'
fi

rm -r -- "$tmp"

exit 0
