#!/bin/bash

## duckdns - update duckdns.org DDNS service
## Usage: duckdns [-d]  # -d adds a timestamp in the log
##  domain and token variables need to be set below

## Example crontab lines (replace /PATH_TO by the actual path of the script):
##  0 0 * * * /PATH_TO/duckdns -d
##  */15 * * * * /PATH_TO/duckdns

## The subdomain of duckdns.org and the token
domain=''
token=''

duckdir="$HOME"
log="$duckdir/duckdns.log"
msg="$duckdir/duckdns.msg"
[[ -f "$log" ]] || echo -n "Log duckdns" >"$log"
[[ -f "$msg" ]] || touch "$msg"
ip='' res=''
url="https://www.duckdns.org/update?domains=$domain&token=$token&verbose=true"

Long(){
	res=$(wget -qO- $url)
	ip=$(grep -o '[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*' <<<$res)
	! grep -q "$ip" <<<$(tail -1 "$msg") && echo $res >>"$msg" && echo -ne "\n $ip" >>"$log"
}

[[ $1 = -d ]] && echo -ne "\n$(date '+%Y-%m-%d')" >>"$log"
Long
if [[ ${res:0:2} = OK ]]
then
	echo -n '~' >>"$log"
else
	echo -n 'X' >>"$log"
	Long
	[[ $res && ! ${res:0:2} = OK ]] && echo -e "\n#"$res >>"$log"
fi

exit 0
