#!/bin/bash
set -xv
## earthwallpaperlive - Set desktop background to earth image
##
## Usage: earthwallpaperlive [-p] [<projection>]
##   -p:  pause for 10 seconds to settle the net connection
##   <projection> is one of: mercator (default), peters, rectangular, random
##
## Required: wget; pgrep (procps); rm, mv, sleep, sync (coreutils);
##   [for peters projection] convert (imagemagick); [app for setting wallpaper]
##
## A cron job could be setup (crontab -e) to run every hour automatically:
##  * 44 * * * /PATH/TO/earthwallpaperlive
## The script has to have execute permissiom then:
##  chmod +x /PATH/TO/earthwallpaperlive

Help(){
	cat <<-EOH
		earthwallpaperlive - Set desktop background to earth image
		Usage: earthwallpaperlive [-h|--help] | [-p] [<projection>]
		  -p: pause for 10 seconds to settle the net connection
		  <projection> is one of: mercator (default), peters, rectangular, random
		  -h/--help:  display this help text
	EOH
	exit 0
}

Wallpaper(){  # $1: imagefile
	if pgrep -f mate-settings-daemon >/dev/null
	then DISPLAY=':0.0' gsettings set org.mate.background picture-filename "$1"
		xcaja=$(xwininfo -name x-caja-desktop)
		xid=$(grep '^xwininfo' <<<$xcaja |cut -d' ' -f4)
		xdotool windowunmap $xid; sleep 1; xdotool windowmap $xid
	elif pgrep -f cinnamon-session >/dev/null
	then gsettings set org.cinnamon.desktop.background picture-uri "file://$1"
	elif pgrep -f gnome-session >/dev/null
	then gsettings set org.gnome.desktop.background picture-uri "file://$1"
	elif pgrep -f xfce4-session >/dev/null
	then
		xfconf-query --channel xfce4-desktop --property \
				/backdrop/screen0/monitor0/image-path --set "$1" 2>/dev/null
		xfconf-query --channel xfce4-desktop --property \
				/backdrop/screen0/monitor0/workspace0/last-image --set "$1" 2>/dev/null
	elif type -p feh >/dev/null
	then feh --bg-fill "$1"
	elif type -p nitrogen >/dev/null
	then nitrogen --set-zoom-fill "$1"
	elif type -p bgs >/dev/null
	then bgs "$1"
	elif type -p hsetroot >/dev/null
	then hsetroot -fill "$1"
	elif type -p habak >/dev/null
	then habak -mS "$1"
	elif [[ $(uname) = "Darwin" ]]
	then osascript -e \
			"Tell 'Finder' to set desktop picture to POSIX file '${1/#\~/$HOME}'"
	else  # trying GNOME..?
		gsettings set org.gnome.desktop.background picture-uri "file://$1"
	fi
}

Main(){
	[[ $1 = -h || $1 = --help ]] && Help
	! type -p wget >/dev/null && echo "ERROR: wget required" && return 1
	pause=0
	[[ $1 = "-p" ]] && pause=1 && shift
	[[ $1 ]] && proj=$1 && shift
	[[ $1 = "-p" ]] && pause=1 && shift
	[[ $1 ]] && echo "ERROR: surplus arguments '$*'" && return 2

	# default is the first element, random the last
	p=(mercator peters rectangular random)
	printf '%s\n' ${p[@]} |grep -q "^$proj$" || proj=$p  ## if not found: default
	[[ $proj = random ]] && proj=${p[$((RANDOM%(${#p[@]}-1)))]}

	pictmp=/tmp/earthwallpaperlive.jpg
	pic=/home/pp/earthwallpaperlive.jpg

	# available dimensions: 1600x770/887 1280x616 1024x493
	width=1600
	((pause)) && sleep 10
	wget -qpO "$pictmp" -w 10 --connect-timeout=20 \
			"https://static.die.net/earth/$proj/$width.jpg"
	# If temporarily unavailable, skip
	(($?==8)) && return 1
	[[ -s $pictmp ]] && cp "$pictmp" "$pic" || return 2
	sleep 1
	sync
	sleep 1

	# For peters cut 26 pixels from top and bottom
	[[ $proj = peters ]] && type -p convert >/dev/null &&
		convert "$pic" +repage -trim -fuzz 90% +repage "$pic"

	Wallpaper "$pic" >/dev/null

	return 0
}

Main "$@"
