#!/bin/bash
set +xv
## earthwallpaperlive
##
## USAGE: earthwallpaperlive [<projection>]
##   <projection> is one of: mercator (default), peters, rectangular, random
##
## Required: wget; pgrep (procps); rm, mv, sleep (coreutils);
##   [for peters projection] convert (imagemagick); [app for setting wallpaper]
##
## A cron job could be setup (crontab -e) to run every hour automatically:
##  * 44 * * * /PATH/TO/earthwallpaperlive
## The script has to have execute permissiom then:
##  chmod +x /PATH/TO/earthwallpaperlive


Wallpaper(){  # $1: imagefile
	if pgrep -f mate-settings-daemon >/dev/null
	then DISPLAY=':0.0' gsettings set org.mate.background picture-filename "$1"
	elif pgrep -f cinnamon-session >/dev/null
	then gsettings set org.cinnamon.desktop.background picture-uri "file://$1"
	elif pgrep -f gnome-session >/dev/null
	then gsettings set org.gnome.desktop.background picture-uri "file://$1"
	elif pgrep -f xfce4-session >/dev/null
	then
		xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set "$1" 2>/dev/null
		xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set "$1" 2>/dev/null
	elif type -p feh >/dev/null
	then feh --bg-fill "$1"
	elif type -p nitrogen >/dev/null
	then nitrogen --set-zoom-fill "$1"
	elif type -p bgs >/dev/null
	then bgs "$1"
	elif type -p hsetroot >/dev/null
	then hsetroot -fill "$1"
	elif type -p habak >/dev/null
	then habak -mS "$1"
	elif [[ $(uname) = "Darwin" ]]
	then osascript -e "Tell 'Finder' to set desktop picture to POSIX file '${1/#\~/$HOME}'"
	else  # trying GNOME..?
		gsettings set org.gnome.desktop.background picture-uri "file://$1"
	fi
}


Main(){
	type -p wget >/dev/null || return 1

	# default is the first element, random the last
	p=(mercator peters rectangular random)
	proj=$1
	printf '%s\n' ${p[@]} |grep -q "^$proj$" || proj=$p
	[[ $proj = random ]] && proj=${p[$((RANDOM%(${#p[@]-1)}))]}

	dir=/tmp
	pic=$dir/earthwallpaperlive.jpg

	# available dimensions: 1600x770/887 1280x616 1024x493
	width=1600
	wget -qpO "$pic" "https://static.die.net/earth/$proj/$width.jpg"
	sleep 1

	# For peters cut 26 pixels from top and bottom
	[[ $proj = peters ]] && type -p convert >/dev/null &&
		convert "$pic" +repage -trim -fuzz 90% +repage "$pic"

	Wallpaper "$pic" >/dev/null

	return 0
}

Main "$@"
