#!/bin/bash

# getjulia - Installing Julia from the generic binaries
# Usage: getjulia [-u|--uninstall | -p|--purge]]
#   -u/--uninstall:  Remove Julia
#   -p/--purge:      Remove Julia and also all user directories
# Environment:
# - TMP (optional): root path of the temporary working directory
# - USR (optional, default: /usr/local): install location
# Required: wget tar coreutils(mktemp rm mv)

# Long-term support release: v.1.0.5
binaries='https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.5-linux-x86_64.tar.gz'
# Current stable release: v1.3.0
binaries='https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-linux-x86_64.tar.gz'

[[ $- = *i* ]] && echo "Run like: sudo bash $BASH_SOURCE" && return 1

usr=${USR:-/usr/local} ics=share/icons/hicolor/scalable/apps
uninstall=0 purge=0
[[ $1 = -u || $1 = --uninstall || $1 = uninstall ]] && uninstall=1
[[ $1 = -p || $1 = --purge || $1 = purge ]] && purge=1 uninstall=1
if ((uninstall))
then
	((UID)) && echo "Privileges needed!"
	sudo rm -fv -- "$usr"/bin/julia
	sudo rm -rfv -- "$usr"/include/julia
	sudo rm -rfv -- "$usr"/lib/julia
	sudo rm -fv -- "$usr"/share/appdata/julia.appdata.xml
	sudo rm -fv -- "$usr"/share/applications/julia.desktop
	sudo rm -rfv -- "$usr"/share/doc/julia
	sudo rm -fv -- "$usr"/"$ics"/julia.svg
	sudo rm -rfv -- "$usr"/share/julia
	sudo rm -fv -- "$usr"/share/man/man1/julia.1
	((purge)) && sudo rm -rfv -- \
			/home/*/.julia /home/*/.juliarc.jl /etc/julia /root/.julia /root/.juliarc.jl
else
	tar=${binaries##*/} tmp=$(mktemp --tmpdir="$TMP" -d getjulia-XXXXXX)
	trap "sudo rm -rf -- '$tmp'" QUIT EXIT INT

	wget -qP "$tmp" "$binaries" -O- |tar xzC "$tmp"
	d=$tmp/${tar%-linux*}

	sudo mkdir -p -- "$usr"/bin /etc/julia "$usr"/include "$usr"/lib
	sudo mkdir -p -- "$usr"/share/appdata "$usr"/share/applications "$usr"/share/doc
	sudo mkdir -p -- "$usr"/"$ics" "$usr"/share/man/man1
	sudo chown -R root:root -- "$d"
	sudo mv -f "$d"/bin/julia "$usr"/bin/ &&
		echo "INSTALLED: $usr/bin/julia"
	sudo mv -n "$d"/etc/julia/startup.jl /etc/julia/ &&
		echo "INSTALLED: /etc/julia/startup.jl"
	sudo rm -rf "$usr"/include/julia
	sudo mv "$d"/include/julia "$usr"/include/ &&
		echo "INSTALLED: $usr/include/julia"
	sudo rm -rf "$usr"/lib/julia
	sudo mv -f "$d"/lib/* "$usr"/lib/ &&
		echo "INSTALLED: $usr/include/julia"
	sudo mv -f "$d"/share/appdata/julia.appdata.xml "$usr"/share/appdata/ &&
		echo "INSTALLED: $usr/share/appdata/julia.appdata.xml"
	sudo mv -f "$d"/share/applications/julia.desktop "$usr"/share/applications/ &&
		echo "INSTALLED: $usr/share/applications/julia.desktop"
	sudo rm -rf "$usr"/share/doc/julia
	sudo mv "$d"/share/doc/julia "$usr"/share/doc/ &&
		echo "INSTALLED: $usr/share/doc/julia"
	sudo mv -f "$d"/"$ics"/julia.svg "$usr"/"$ics"/ &&
		echo "INSTALLED: $usr/$ics/julia.svg"
	sudo rm -rf "$usr"/share/julia
	sudo mv "$d"/share/julia "$usr"/share/ &&
		echo "INSTALLED: $usr/share/julia"
	sudo mv -f "$d"/share/man/man1/julia.1 "$usr"/share/man/man1/ &&
		echo "INSTALLED: $usr/share/man/man1/julia.1"
fi

exit 0
