#!/usr/bin/env bash
set -xe
# gomod-update - Update modules in go projects
# Required: go git coreutils(rm) nano grep goreleaser
# Usage gomod <tool>

pkgs=becrypt/bat/horcrux/m2m/mailer/twofat

[[ -z $1 ]] &&
	echo "Need one or more from $pkgs as argument" &&
	exit 1

# Check: becrypt bat? horcrux m2m mailer? twofat
for dir in $@
do
	[[ ! /$pkgs/ = */$dir/* ]] &&
		echo "Package not one of: $pkgs" &&
		continue
	cd /data/git/"$dir"
	rm go.mod
	go mod init github.com/pepa65/"$dir"
	go mod tidy
	# If go.sum same, checkout go.mod and bail
	[[ -z $(git diff -- go.sum) ]] &&
		git checkout go.mod &&
		echo "====== No module updates" &&
		continue

	read -p "Ctrl-C to abort, or Enter to update the VERSION in main.go and README.md"
	nano main.go README.md  # increase to VERSION manually
	go install
	_=$($dir -h 2>&1 |grep -o '^[^ ]* v[.0-9]*') version=${_#$dir }
	git commit -a -m "Modules update"
	git tag -a $version
	git push
	goreleaser --clean
done
