#!/usr/bin/env bash
set +x -e  # Stop on any error
# gomod-update - Update modules in Go projects
# Required: find grep sed go git goreleaser coreutils(cd rm head)
# Usage:  gomod-update [-h|--help] | [-n|--norun] [-r|--release PKG] | -a|--all | PKG...

git=$HOME/git/ readme=README.md mod=go.mod sum=go.sum main=main.go

# Check flags
all=0 help=0 norun=0 release=0 multiple=0 pkgs= title=
(($#==0)) &&
	help=1
for a in "$@"
do
	((release)) && [[ -z $title ]] &&
		title=$a &&
		continue
	case $a in
	-an|-na) norun=1 all=1 ;;
	-h|--help) help=1 ;;
	-a|--all) all=1 ;;
	-r|--release)
		((release)) &&
			echo "### Release can only be given once" &&
			exit 1
		release=1 ;;
	-n|--norun) norun=1 ;;
	*)
		[[ -z $pkgs ]] &&
			pkgs=$a ||
			pkgs+=" $a" multiple=1
	esac
done
((all && release)) &&
	echo "### Release and All can not both be given" &&
	exit 1

if ((release))
then
	[[ -z $title ]] &&
		echo "### Release must have a title, as in: --release TITLE PKG" &&
		exit 1

	((multiple)) &&
		echo "### Release can only have 1 package, as in: --release TITLE PKG" &&
		exit 1
fi

[[ -z $pkgs && $norun = 1 ]] &&
	all=1

# Show suitable Go projects
declare -A packages
for f in $(find "$git" |grep "/$mod$")
do
	repo=$(cd ${f%$mod}; [[ -d .git ]] &&
			git remote -v |grep '^origin' |grep ' (push)$' |grep 'github\.com.pepa65/' |head -1) &&
		grep -q '^module github.com/pepa65/' "$f" &&
		[[ -f ${f%$mod}$main ]] &&
		v=$(grep 'version [ ]*= "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"$' "${f%$mod}$main") &&
		v=${v##* } v=${v//\"} p=${f#$git} p=${p%/$mod} &&
		packages[$p]=$v
done
((${#packages[@]}==0)) &&
	echo "### No suitable packages found" &&
	exit 1

packages=$(grep -o '[^ ]*' <<<${!packages[@]} |sort |tr $'\n' ' ')
packages=${packages%?}
echo -e "--- Suitable packages:\n    $packages\n"
((help)) &&
	echo "--- Usage:  ${0##*/} [-h|--help] | [-n|--norun] [-r|--release COMMIT_TILE PKG] -a|--all | PKG..." &&
	exit

((all)) &&
	set -- $packages ||
	set -- $pkgs
updates=
declare -A failed
for pkg in $@
do
	[[ ! ,${packages// /,}, = *,$pkg,* ]] &&
		echo -e "### Given package not suitable: $pkg\n" &&
		continue

	# Check update
	echo "--- Check for module updates: $pkg"
	cd "$git$pkg"
	rm "$mod"
	update=$(go mod init "github.com/pepa65/$pkg" 2>&1 |head -1)
	go mod tidy
	# If go.sum same, checkout go.mod and bail
	if [[ -z $(git diff -- $sum) ]]
	then
		git checkout $mod 2>/dev/null
		((!release)) &&
			echo -e "=== No module updates: $pkg\n" &&
			continue ||
			echo "--- Ignoring module updates"
	fi

	((release && norun)) &&
   	echo &&
    continue

	updates+="$pkg "
	failed[$pkg]=1
	if ((!release))
	then
		echo -e "=== Updates found: $pkg\n$(head -1 <<<"$update")"
  	((norun)) &&
    	echo &&
	    continue
	fi

	curr=${packages[$pkg]}
	((release)) &&
		ver=${curr%.*} ver=${ver##*.} vp1=$((ver+1)) new=${curr%%.*}.$vp1.0 ||
		patch=${curr##*.} pp1=$((patch+1)) new=${curr%.*}.$pp1
	echo "--- Patching from $curr to $new"
	! sed -i "s/ \"$curr\"/ \"$new\"/" $main &&
	  echo -e "### Version update in main.go unsuccesful: $pkg\n" &&
	  continue

	! sed -i "s/$curr/$new/" $readme &&
	  echo -e "### Version update in $readme unsuccesful: $pkg\n" &&
		continue

	CGO_ENABLED=0 go install -ldflags="-s -w"
	rm -f ~/bin/$pkg
	cp ~/go/bin/$pkg ~/bin/
	upx --best --lzma ~/bin/$pkg
	: ${title:=Update deps}
	git commit -a -m "$title"
	git tag v$new -m $new
	git push origin --all
	goreleaser --clean
	echo -e "=== Update successful: $pkg\n"
	unset failed[$pkg]
done

if [[ $updates ]]
then
	echo "=== Updates found: $updates"
[[ $failed ]] &&
	echo "### Update failed: ${failed[@]}" ||
	echo "=== No updates failed"
else
	echo "=== No updates found at all"
fi

