#!/usr/bin/env bash
set -e #-x
# gomod-update - Update modules in go projects
# Required: go git coreutils(rm head) nano grep goreleaser
# Usage gomod-update <tool>

pkgs=becrypt/bat/horcrux/m2m/mailer/twofat

[[ -z $1 ]] &&
	echo "Need one or more from $pkgs as argument" &&
	exit 1

# Check: becrypt bat? horcrux m2m mailer? twofat
for dir in $@
do
	[[ ! /$pkgs/ = */$dir/* ]] &&
		echo "Package not one of: $pkgs" &&
		continue
	gitdir=/data/git/$dir
	cd "$gitdir"
	rm go.mod
	go mod init github.com/pepa65/"$dir"
	go mod tidy
	# If go.sum same, checkout go.mod and bail
	[[ -z $(git diff -- go.sum) ]] &&
		git checkout go.mod &&
		echo "====== No module updates" &&
		continue
	echo "Ctrl-C to abort, or Enter to update the VERSION in $gitdir"
	echo "(the files 'main.go' and 'README.md' will be opened in nano to edit)"
	read
	nano main.go README.md  # increase to VERSION manually in the editor
	go install
	version=$(~/go/bin/$dir -h 2>&1 |grep -o 'v[.0-9]*' |head -1)
	git commit -a -m "Modules update"
	git tag $version -m $version
	git push origin $version --all
	goreleaser --clean
done
