#!/bin/bash

# kbt2bitwarden - Enter keepassx text into bitwarden .csv format:
#  <group>,,login,<name>,<notes>,,<url>,<user>,<pw>,^M
# Usage: kbt2bitwarden <Text Export from Keepass1>

[[ ! -f $1 ]] && echo "Need .kbt file from KeepassX" && exit 1
[[ -f $1.csv ]] && echo "File '$1.csv'exists, not overwriting" && exit 2

echo "folder,favorite,type,name,notes,fields,login_uri,login_username,login_password,login_totp"$'\xd' >"$1.csv"

group=
while read -r
do
	r=$REPLY
	case "$r" in
		'*** Group: '*) [[ $group ]] &&  # Unprocessed previous entry
				echo "$group,,login,$name,\"${notes//\"/\"\"}\",,$url,$user,$pw,"$'\xd' >>"$1.csv"
			group=${r:11} group=${group% ???} name= ;;
		'  Title:    '*)
			[[ $name ]] &&  # Unprocessed previous entry
				echo "$group,,login,$name,\"${notes//\"/\"\"}\",,$url,$user,$pw,"$'\xd' >>"$1.csv"
			name=${r:12} notes= ;;
		'  Username: '*) user=${r:12} ;;
		'  Url:      '*) url=${r:12} ;;
		'  Password: '*) pw=${r:12} ;;
		'  Comment:  '*) notes=${r:12} ;;
		'            '*) notes+=$'\n'${r:12} ;;
	esac
done <"$1"

# Output final entry
echo "$group,,login,$name,\"${notes//\"/\"\"}\",,$url,$user,$pw,"$'\xd' >>"$1.csv"

exit 0
