#!/bin/bash
set +vx
# pdfslice - Make pdf from page ranges in a source document
# Usage: pdfslice <from> <to> <source.pdf> [<destination.pdf>]
# Required: pdfseparate pdfunite coreutils(mktemp cd)

Help(){ # $1:message
	echo "$Self - Make pdf from page ranges in a source document"
	echo "Usage:  $Self [-h|--help ] | <from> <to> <source.pdf> [<destination.pdf>]"
	echo "    where <from> and <to> are the first and last page number"
	echo "  -h/--help:  display this help text"
	[[ $1 ]] && echo -e "\n$1" && exit 1
	exit 0
}

Self=${0##*/}
[[ $1 = -h || $1 = --help ]] && Help
(($#!=3 && $#!=4)) && Help "ERROR: $Self must have 3 or 4 arguments"
from=$1 to=$2 src=$3
((from<=0)) && Help "ERROR: First page not positive: $from"
((to<=0)) && Help "ERROR: Last page not positive: $to"
((from>to)) && Help "ERROR: First page $from larger than last page $to"
[[ ! -f $src ]] && Help "ERROR: pdf file '$src' not found"
[[ $4 ]] && dest=$4 || dest="$(basename "$src" .pdf)_$from-$to.pdf"

tmp=$(mktemp -d)
pdfseparate -f "$from" -l "$to" "$src" "$tmp/p%d"
[[ -z $(ls -LF) ]] && Help "ERROR: No pages $from-$to found in $src"

shopt -s nullglob
pdfunite "$tmp"/p? "$tmp"/p?? "$tmp"/p??? "$tmp"/p???? "$tmp"/p????? "$dest"
shopt -u nullglob
rm -r -- "$tmp"

exit 0
