#!/bin/bash
set +xv
## rmkernels - remove extraneous kernels from /boot on Ubuntu based systems
## Usage: bash rmkernels [-f]
##  (if the -f option is given, newer than currently running can be removed)

main(){
	a="$(ls -1 /boot/vmlinuz-* |
			sed 's@^/boot/vmlinuz-@@' |
			grep -v '\.efi\.signed' |
			sort -nr)" ## All	installed images according to name
	c=$(uname -r)  ## Currently running kernel version
	n="$(grep -v "$c" <<<"$a")" ## Non-running installed images
	echo -e "Found kernel images:\n$c (currently running)\n$n"
	## Superfluous versions: keep only the latest of same major.minor version of
	## non-running kernels
	s=$(while IFS='.' read a b c
		do
			[[ $ao = $a && $bo = $b ]] && echo "$a.$b.${c%-*}"
			ao=$a bo=$b
		done <<<"$n")
	if [[ $s ]]
	then
		echo -e "Removing:\n$s\n"
		## Check if an older kernel is currently running
		while read k
		do
			[[ $c < $k ]] && newer+="$k\n"
		done <<<"$s"
		if [[ $newer ]]
		then
			echo -e "Found installed kernels newer than currently running:\n$newer"
			[[ ! $1 = -f ]] && echo "Run with '-f' to force this" && exit 1
		fi
		## Purge all that is found with these superfluous versions
		p=$(dpkg -l | grep "-e ${s// / -e }" | cut -d' ' -f3)
		sudo apt purge $p
	else
		echo "Nothing to remove"
	fi
}

main $*
