#!/bin/bash

## rmkernels -- remove extraneous kernels from /boot on Ubuntu bases systems
## usage: source rmkernels (or: bash rmkernels)

main(){
	a="$(ls -1 /boot/vmlinuz-* |
			sed 's@^/boot/vmlinuz-@@' |
			grep -v '\.efi\.signed' |
			sort -nr)" ## all	
	c=$(uname -r)  ## currently running kernel version
	r="$(grep -v "$c" <<<"$a")" ## rest
	echo -e "$c (currently running)\n$r"
	## Superfluous versions: keep only the latest of same major.minor version of
	## the rest of the kernels
	s=$(ao= bo=
		while IFS='.' read a b c
		do
			[[ $ao = $a && $bo = $b ]] && echo "$a.$b.${c%-*}"
			ao=$a bo=$b
		done <<<"$r")
	if [[ $s ]]
	then
		echo -e "Remove:\n$s\n"
		(while read k
			do
				[[ $c < $k ]] && {
					echo "But $k is more recent than currently running!"
					[[ ! $1 = -f ]] && echo "Run with '-f' to force this" && exit 1
			done) <<<"$s"
		g=$(sed 's/ /\\|/g' <<<$s)
		p=$(dpkg -l | grep "$g" | cut -d' ' -f3)
		sudo apt purge $p
	else
		echo "Nothing to remove"
	fi
}

main $*
