#!/usr/bin/env bash
# song2png - Convert song to png
# song format:
# - First line is the title (will be bolded)
# - Every empty line yields a paragraph
# - Every '['...']' clause will be italicized and grayed
# - Skip lineas starting with a '!'
# Usage:  song2png SONG.txt [PATH]
#  Output will be the .txt extension replaced (if present) or appended by .png into PATH
# Required: chromium imagemagick(mogrify) coreutils(mktemp cat ls)

Usage(){ # 1:error
	cat <<-EOM
		song2png - Convert .txt input file (first argument) to .png in PATH
		Usage:  song2png SONG.txt [PATH]
		  Format of SONG.txt:
		  - Fist line:     Title
		  - Empty line:    Paragraph separator
		  - Start with !:  Skipped
		  - [...]:         Italicized & grayed
	EOM
	[[ -z $1 ]] &&
		exit

	echo -e "\nAbort: $1" &&
	exit 1
}

[[ ! $1 ]] &&
	Usage

song=$1 path=$2
[[ ! -f $song ]] &&
	Usage "Input file '$song' not found"

png=${song%.txt}.png
[[ $path && -d $path ]] &&
	png=$path/${png##*/} ||
	png=$path
htm=$(mktemp --suffix=.htm)

Starthtml() { # I:title,htm
	cat <<-EOH >"$htm"
		<!DOCTYPE html>
		<title>$title</title>
		<style>
		body{font-family:"Garuda",serif; font-size:16pt; font-kerning:normal; line-height:20pt;}
		i{font-size:80%; font-style:italic; color:#aaa;}
		@page{size:399mm 1999mm; margin:.4in;}
		</style>
		<p><b>$title</b>
	EOH
	echo -n "<p>" >>"$htm"
}

title=
while read line
do # Process line
	[[ ${line:0:1} = ! ]] &&
		continue

	[[ -z $title ]] &&
		title=$line &&
		Starthtml &&
		continue

	[[ -z $line ]] &&
		echo -n "<p>" >>"$htm" &&
		continue

	line=${line//[/<i>[} line=${line//]/]</i>}
	echo "$line<br>" >>"$htm"
done <"$song"

chromium --headless=new --window-size=1024,4096 --disable-gpu --disable-software-rasterizer --enable-chrome-browser-cloud-management --force-device-scale-factor=2 --screenshot="$png" "$htm" 2>/dev/null
rm "$htm"
mogrify -depth 3 -trim +repage -bordercolor white -border 24 -define png:color-type=3 "$png"
