#!/usr/bin/env bash
# song2png - Convert song to png
# song format:
# - First line is the title (will be bolded)
# - Every empty line yields a paragraph
# Usage:  song2png <songfile>
#  Output will be the .txt extension replaced (if present) or appended by .png
# Required: chromium imagemagick(mogrify) coreutils(mktemp cat ls)

song=$1
[[ ! -f $song ]] &&
	echo "Abort: Input file '$song' not found" &&
	exit 1

htm=$(mktemp --suffix=.htm) png=${song%.txt}.png

Starthtml() { # I:title,htm
	cat <<-EOH >"$htm"
		<!DOCTYPE html>
		<title>$title</title>
		<style>
		body{font-family:"Garuda",serif; font-size:16pt; font-kerning:normal;}
		i{font-size:90%; font-style:normal; color:#888;}
		@page{size:299mm 999mm; margin:.4in;}
		</style>
		<p><b>$title</b>
	EOH
	echo -n "<p>" >>"$htm"
}

title=
while read line
do # Process line
	[[ -z $title ]] &&
		title=$line &&
		Starthtml &&
		continue

	[[ -z $line ]] &&
		echo -n "<p>" >>"$htm" ||
		echo "$line<br>" >>"$htm"
done <"$song"

chromium --headless=new --window-size=512,4096 --disable-gpu --enable-chrome-browser-cloud-management --force-device-scale-factor=1 --screenshot="$png" "$htm"
rm "$htm"
mogrify -depth 3 -trim +repage -bordercolor white -border 24 -define png:color-type=3 "$png"
