#!/usr/bin/env bash
set -vx
# song2png - Convert SONG.txt to [PNG or] SONG.png [in DIR]
# song format:
# - First line is the title (will be bolded)
# - Every empty line yields a paragraph
# - Every '['...']' clause will be italicized and grayed
# - Skip lineas starting with a '!'
# Usage:  song2png SONG.txt [PATH]
#  Output will be the .txt extension replaced (if present) or appended by .png into PATH
# Required: chromium|google-chrome-* imagemagick(mogrify) coreutils(mktemp cat ls)

Usage(){ # 1:error
	cat <<-EOM
		song2png - Convert SONG.txt to [PNG or] SONG.png [in DIR]
		Usage:  song2png SONG.txt [PNG|DIR]
		  Format of SONG.txt:
		  - Fist line:     Title
		  - Empty line:    Paragraph separator
		  - Start with !:  Skipped
		  - [...]:         Italicized & grayed
	EOM
	[[ -z $1 ]] &&
		exit

	echo -e "\nAbort: $1" &&
	exit 1
}

[[ ! $1 ]] &&
	Usage

txt=$1 path=$2
[[ ! -f $txt ]] &&
	Usage "Input file '$txt' not found"

for chrom in chromium google-chrome-{stable,beta,unstable,canary} __X
do
	type -p $chrom &&
		break
	[[ $chrom = __X ]] &&
		echo "Abort: no chromium/chrome binary found" &&
		exit 2
done

png=${txt%.txt}.png
if [[ $path ]]
then
	[[ -d $path ]] &&
		png=$path/${png##*/} ||
		png=$path
fi
htm=$(mktemp --suffix=.htm)

Starthtml() { # I:title,htm
	cat <<-EOH >"$htm"
		<!DOCTYPE html>
		<title>$title</title>
		<style>
		body{font-family:"Garuda",serif; font-size:16pt; font-kerning:normal; line-height:20pt;}
		i{font-size:80%; font-style:italic; color:#aaa;}
		@page{size:399mm 1999mm; margin:.4in;}
		</style>
		<p><b>$title</b>
	EOH
	echo -n "<p>" >>"$htm"
}

title=
while read line
do # Process line
	[[ ${line:0:1} = ! ]] &&
		continue

	[[ -z $title ]] &&
		title=$line &&
		Starthtml &&
		continue

	[[ -z $line ]] &&
		echo -n "<p>" >>"$htm" &&
		continue

	line=${line//[/<i>[} line=${line//]/]</i>}
	echo "$line<br>" >>"$htm"
done <"$txt"

# htm2png
$chrom --headless=new --window-size=1024,4096 --disable-gpu --disable-software-rasterizer --enable-chrome-browser-cloud-management --force-device-scale-factor=2 --screenshot="$png" "$htm" 2>/dev/null &&
	rm "$htm" &&
	mogrify -depth 3 -trim +repage -bordercolor white -border 24 -define png:color-type=3 "$png"
