#!/usr/bin/env bash
# song2pdf - Convert song to pdf
# song format:
# - First line is the title (will be bolded)
# - Every empty line yields a paragraph
# Usage:  song2pdf <songfile>
#  Output will be the .txt extension replaced (if present) or appended by .pdf
# Required: typst coreutils(mktemp cat ls)

song=$1
[[ ! -f $song ]] &&
	echo "Abort: Input file '$song' not found" &&
	exit 1

ty=$(mktemp --suffix=.ty) pdf=${song%.txt}.pdf

Starttypst() { # I:title,ty
	cat <<-EOH >"$ty"
		#set page(width:auto, height:auto, margin:4mm)
		#set align(center)
		#set text(font:"Garuda")
		=== $title
	EOH
}

title=
while read line
do # Process line
	[[ -z $title ]] &&
		title=$line &&
		Starttypst &&
		continue

	[[ -z $line ]] &&
		echo >>"$ty" ||
		echo "$line\\" >>"$ty"
done <"$song"

typst c "$ty" "$pdf"
ls -l "$pdf"
