#!/usr/bin/perl -w

# tn - Try TCP on host & port

use strict;
use IO::Socket;

my $usage = "Usage: ${0} <host> <port>\n";

my $host = shift or die $usage;
my $port = shift or die $usage;
gethostbyname($host) || die "Invalid host: $host\n";

my $handle = IO::Socket::INET->new(
		PeerAddr => $host,
		PeerPort => $port,
		Proto => 'tcp')
	or die "closed\n";
close $handle;
print "open\n"
