#!/bin/bash

# xran - Arrange 2 screens with different pixel densities beside each other

Help(){
	cat <<-EOH
		xran - Arrange 2 screens with different pixel densities beside each other
		Usage: xran [-h|-f] [<ldisp> [<rdisp>]] [<lperc> [<rperc>]] [+|-<offset>]
		  -h|--help:   Just display this help text
		  -f|--force:  Execute the xrandr command (otherwise just display it)
		Default parameters:  eDP-1 HDMI-1 70 110 +0  (used when not specified)
		  <ldisp>, <rdisp>:  Names of the left and right displays, must start with
		                     alphabetical character.
		  <lperc>, <rperc>:  Scaling of left and right display in whole percentages
		  +|-<offset>:       Vertical alignment of the top edge of the screens,
		                     must have '+' or '-' (positive: left display is lower)
	EOH
}

Xran(){ # $1:leftdisplay $2:rightdisplay $3:leftperc $4:rightperc $5:offset
	# parameter defaults (no parameters: help)
	local n=0 force=0 ld=eDP-1 rd=HDMI-1 lp=70 rp=110 vo=+0 top
	local ldset=0 rdset=0 lpset=0 rpset=0 voset=0
	Pr(){ # $1:leftdisplay $2:rightdisplay $3:leftperc $4:rightperc $5:offset
		local rx=$((1920*$3/100)) lpos rpos lp rp
		(($3<100)) && lp=.$3 || lp=${3:0:1}.${3:1}
		(($4<100)) && rp=.$4 || rp=${4:0:1}.${4:1}
		(($5<0)) &&
			lpos="0x0" rpos="${rx}x${5:1}" ||
			lpos="0x$5" rpos="${rx}x0"
		echo -n "xrandr --output $1 --auto --scale ${lp}x$lp --mode 1920x1080"
		echo -n " --fb 3840x2160 --pos $lpos --primary --output $2 --auto"
		echo " --scale ${rp}x$rp --mode 1920x1080 --pos $rpos"
	}
	while (($#))
	do
		case $1 in
			-h|--help) Help; return ;;
			-f) force=1 ;;
			[a-zA-Z]*)
				if ((ldset))
				then
					((rdset)) &&
						echo "Can't configure more than 2 displays: $1" && return 1 ||
						rd=$1 rdset=1
				else ld=$1 ldset=1
				fi ;;
			[0-9]*)
				if ((lpset))
				then
					((rpset)) &&
						echo "More than 2 percentages given: $1" && return 2 ||
						rp=$1 rpset=1
				else lp=$1 lpset=1
				fi ;;
			[+-][0-9]*)((voset)) &&
					echo "More that 1 offset specified: $1" && return 3 ||
					vo=$1 voset=1 ;;
			*) echo "Unrecognized argument: $1" && return 4
		esac
		shift
	done
	[[ ! $lp =~ ^[0-9]*$ ]] &&
		echo "Percentage for leftscale can only be numeric: $lp" &&
		return 5
	[[ ! $rp =~ ^[0-9]*$ ]] &&
		echo "Percentage for rightscale can only be numeric: $rp" &&
		return 6
	[[ ! $vo =~ ^[-+][0-9]*$ ]] &&
		echo "Offset must be a signed integer: $offset" && return 7
	((vo>0)) && top="$vo pixels higher"
	((vo<0)) && top="$vo pixels lower"
	((vo==0)) && top="at the same height"
	echo "Display $ld at $lp% on the left side and $rd at $rp% on right side with the top edge $top"
	((force)) &&
		eval $(Pr $ld $rd $lp $rp $vo) && echo "Done" ||
		Pr $ld $rd $lp $rp $vo
}

Xran "$@"
