#!/bin/bash
set +vx
# ypass - the standard unix password manager with GUI
# Requirements: pass coreutils(type sleep shred ls) sed diffutils(diff)

store=~/.password-store
cd "$store"

! type -P pass &>/dev/null && echo "Error: pass needs to be installed" &&
	exit 1
! type -P yad &>/dev/null && echo "Error: yad needs to be installed" &&
	exit 2

rmtemp(){ sleep .2; shred -fu /dev/shm/pass"$$".* 2>/dev/null; return 0;}
trap 'rmtemp' EXIT
trap "rmtemp; trap - HUP; kill -HUP $$" HUP
trap "rmtemp; trap - INT; kill -INT $$" INT
trap "rmtemp; trap - QUIT; kill -QUIT $$" QUIT
trap "rmtemp; trap - TERM; kill -TERM $$" TERM

yad='yad --title=ypass' msg= rc=0 ls= entry='Entry  - - - sort - - -'
while ((rc!=252))
do # No close clicked
	tmp=$(mktemp "/dev/shm/pass$$.XXXXXXXX")
	if [[ $ls ]]
	then
		ls -1F -t $ls |sed 's@\.gpg$@@' \
				|$yad --list --height=750 --width=200 --text="<b>$ls</b>" \
				--response=5 --button=Delete:2 --button=New:3 \
				--button=Search:4 --button=View:5 --button=Back:6 \
				--column=$entry 2>/dev/null >"$tmp"
	else
		ls -1F -t |sed 's@\.gpg$@@' \
				|$yad --list --height=750 --width=200 $msg \
				--response=5 --button=Delete:2 --button=New:3 --button=Search:4 \
				--button=View:5 --column=$entry 2>/dev/null >"$tmp"
	fi
	rc=$? dir=0 sel=$(<"$tmp") sel=${sel%|} msg=
	rmtemp
	[[ ${sel: -1} = / ]] && sel=${sel%/} dir=1
	[[ $ls && $sel ]] && sel=$ls/$sel
	case $rc in
		252) # Close
			exit 0 ;;
		2) # Delete
			if [[ $sel ]]
			then
				[[ ${sel%%/*} = trash ]] &&
					pass rm -r -f "$sel" ||
					pass mv -f "$sel" "trash/$sel"
			fi
			continue ;;
		6) # Back
			[[ $ls == */* ]] && ls=${ls%/*} || ls=
			continue ;;
		5|0) # View or Clicked entry
			((dir)) && ls=$sel && continue ;;
		4) # Search
			$yad --entry --height=80 --width=220 --editable \
					--entry-label="Search terms" 2>/dev/null >"$tmp"
			rc=$?
			((rc==1 || rc==252)) && continue
			sel=$(<"$tmp")
			rmtemp
			echo "This might take a while..." \
				|$yad --text-info --width=260 --text "<b>Searching</b>" --no-buttons &
			pid=$!
			cols=("$(pass grep "$sel" |cat -v \
				|sed -e ':a' -e 'N' -e '$!ba' -e 's@\n@ / @g' \
				|sed -e 's@ / \^\[\[94m\^\[\[1m@\n@g' -e 's@\^\[\[01;31m\^\[\[K@@g' \
						-e 's@\^\[\[m\^\[\[K@@g' -e 's@\^\[\[0m: / @\n@g' \
						-e 's@^\^\[\[94m\^\[\[1m@@')")
			kill -USR1 $pid 2>/dev/null
			[[ -z ${cols[@]} ]] && ls= msg="--text=<b>No results</b>" && continue
			echo "${cols[@]}" |$yad --list --height=750 --width=400 \
					--expand-column=0 --print-column=1 --wrap-cols=2 \
					--column="Entry" --column="Search results" \
					2>/dev/null >"$tmp"
			rc=$?
			((rc==1 || rc==252)) && continue
			sel=$(<"$tmp") sel=${sel%|}
			rmtemp
			[[ $sel ]] || continue
			[[ $ls ]] && sel=$ls/$sel ;;
		3) # New
			sel=
			while [[ -d $store/$ls/$sel ]]
			do
				$yad --entry --height=80 --width=220 --editable \
						--entry-label="New entry name" 2>/dev/null >"$tmp"
				rc=$?
				((rc==1 || rc==252)) && continue 2
				sel=$(<"$tmp")
				rmtemp
			done
			[[ $ls ]] && sel=$ls/$sel
			echo |pass insert -f "$sel" ;;
	esac

	tmp=$(mktemp "/dev/shm/pass$$.XXXXXXXX")
	tmpu=$(mktemp "/dev/shm/pass$$.XXXXXXXX")
	pass show "$sel" >"$tmp"
	$yad --text-info --text="<b>$sel</b>" --height=500 --width=400 \
			--button=Update:6 --button=Back:5 --response=5 \
			--filename="$tmp" --editable --wrap --show-uri 2>&1 >"$tmpu"
	rc=$?
	case $rc in
		6) # Update
			diff -q "$tmp" "$tmpu" && rmtemp && continue
			pass mv -f "$sel" "backup/$sel"
			pass insert -m "$sel" <"$tmpu"
			rmtemp ;;
		5) # Back
			[[ $ls == */* ]] && ls=${ls%/*} || ls= ;;
	esac
done

exit 0
